name: climate
description: Flutter Weather App done by Chaitanya DAMARASINGU.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  

  easy_rich_text: ^1.2.0
  drop_shadow: ^0.0.2+1
  http: ^0.13.5
  provider: ^6.0.5
  intl: ^0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
     - assets/intro.png
     - assets/bg.png
     - assets/cloudy.png
     - assets/logo.png
     - assets/rainy.png
     - assets/shade.png
     - assets/smile.png
     - assets/snow.png
     - assets/storm.png
     - assets/sunny.png
     - assets/thunder.png
     - assets/title.png
     - assets/login_logo.png
     - assets/air.png


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
